on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v1
      name: Checkout Code

    - uses: actions/cache@v1
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }} #hash of project files
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - uses: actions/setup-dotnet@v3
      with:
       dotnet-version: 7.x

    - name: Build 
      run: msbuild Windows/Cyte.sln /p:Configuration=Release /p:DebugSymbols=false /p:DebugType=None /p:PublishReadyToRun=false

    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Cyte
        path: Windows\bin\Release\
